### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by tlaukkan** [andrewnk/docker-alpine-nginx-modsec#3]
Hi

I am getting this error when I try to build:

utils/geo_lookup.cc: In member function 'bool modsecurity::Utils::GeoLookup::lookup(const string&, modsecurity::Transaction*, std::function<bool(int, const std::__cxx11::basic_string<char>&)>) const':
utils/geo_lookup.cc:124:32: error: invalid conversion from 'const MMDB_s*' to 'MMDB_s*' [-fpermissive]
         r = MMDB_lookup_string(&mmdb, target.c_str(), &gai_error, &mmdb_error);
                                ^~~~~
In file included from ../src/utils/geo_lookup.h:22,
                 from utils/geo_lookup.cc:25:
/usr/include/maxminddb.h:204:66: note:   initializing argument 1 of 'MMDB_lookup_result_s MMDB_lookup_string(MMDB_s*, const char*, int*, int*)'
     extern MMDB_lookup_result_s MMDB_lookup_string(MMDB_s *const mmdb,
                                                    ~~~~~~~~~~~~~~^~~~


Kind regards,
Tommi

**Comment by andrewnk** [comment]
Thanks for the heads up! It looks like there is an issue with the current v3/master branch and libmaxminddb. I've added a build arg to pull the v3.0.4 branch which will fix the issue; pull the most recent changes to update. I also noticed in the process that MaxMind now requires a login in order to download their GeoIP db's, so I switched to dbip. Thanks again and let me know if you have any more issues!
