### ISSUE TITLE
Image path no longer correct

### ISSUE THREAD

**Issue by klou** [andrewnk/docker-alpine-nginx-modsec#4]
It's a minor thing, but your released Package (https://github.com/andrewnk/docker-alpine-nginx-modsec/packages/66067) points to a 404 in the Docker registry.

```
FROM docker.pkg.github.com/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec:latest
```

I'm using ```FROM andrewnk/alpine-nginx-modsec``` to pull the image.

Thanks for this, btw.

**Comment by andrewnk** [comment]
I believe you need to be logged into the github registry in order to pull/use that image. I just tested and it appears to work okay:

```bash
$ docker login docker.pkg.github.com
Authenticating with existing credentials...
[...]
Login Succeeded

$ docker pull docker.pkg.github.com/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec:latest
latest: Pulling from andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec
Digest: sha256:3c670fe210043a2c92b88f0c669ea7933de0615cc71570a14ff039cd52106c72
Status: Downloaded newer image for docker.pkg.github.com/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec:latest
docker.pkg.github.com/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec:latest

$ docker logout docker.pkg.github.com
Removing login credentials for docker.pkg.github.com

$ docker pull docker.pkg.github.com/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec:latest
Error response from daemon: Get https://docker.pkg.github.com/v2/andrewnk/docker-alpine-nginx-modsec/docker-alpine-nginx-modsec/manifests/latest: no basic auth credentials
```
If that is the case, I would still suggest using docker hub like you ended up doing above (`FROM andrewnk/alpine-nginx-modsec`). I recently started using git branches to tag images on docker hub, which will provide some flexibility, and I haven't found an easy way to automate that on github yet. Thanks!
